name: Website Tester

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black (check only)
        run: black --check .

      - name: Run Flake8
        run: flake8 .

  test:
    needs: lint-and-format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [ playwright, selenium ]
        browser: [ chrome, firefox, edge ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run tests
        run: |
          python -m src.runners.runner --framework=${{ matrix.framework }} --test-browser=${{ matrix.browser }} --numprocesses=2 --report=allure

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.framework }}-${{ matrix.browser }}
          path: allure-results/