name: Website Tester

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [ playwright, selenium ]
        browser: [ chrome, firefox, edge ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
          playwright install-deps

      - name: Run tests
        run: |
          python -m src.runners.runner --framework=${{ matrix.framework }} --browser=${{ matrix.browser }} --numprocesses=2 --report=allure

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.framework }}-${{ matrix.browser }}
          path: allure-results/